# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 地球冇得救
name: 雕狸狮狒
email: tyl1212@qq.com
location: 宇宙黑洞旁边
company: 专注飞船开光与核弹头抛光技术
company_url: http://www.youtube.com
github_url: https://github.com/follom
description: 专业研究开光与抛光技术300年
favicon: i.png # Image must be in assets/images

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://follom.github.io
#url: http://localhost:4000
url: http://follom.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: follom.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: http://aswew.com
    label: 注册
#  -
#    href: /open-source
#    label: Open-Source

#  -
#    href: /blog
#    label: Blog

  -
    href: /bookmark
    label: 登陆
  -
    href: /about
    label: 关于
# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
# analytics :
#  provider : google
#  google :
#      tracking_id : 'UA-80236653-1'


# For about.html. Fell free to create your own!
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, ReactJS, PrototypeJS, NodeJS, ExpressJS, MongoDB, Boostrap]
skill_mobile_hybrid_app_keywords: [Cordova, Phonegap, Ionic]

theme: jekyll-theme-cayman